// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApcEFQaqbyjI47R0RjVQ8aBb6JnmqN0fE',
    appId: '1:862022709072:web:4bf0080d7c1be90b4d0655',
    messagingSenderId: '862022709072',
    projectId: 'flash-chat-3c761',
    authDomain: 'flash-chat-3c761.firebaseapp.com',
    storageBucket: 'flash-chat-3c761.firebasestorage.app',
    measurementId: 'G-1KJRTQ2JXE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmTD6tY0qCGQRhBEk9-Z9T8uEA13ICQdU',
    appId: '1:862022709072:android:fca642d56c9ef4ed4d0655',
    messagingSenderId: '862022709072',
    projectId: 'flash-chat-3c761',
    storageBucket: 'flash-chat-3c761.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwRmnsOJV3KyQO5nWCQ5EqFIeVMn-vgYU',
    appId: '1:862022709072:ios:7ea3359c926209294d0655',
    messagingSenderId: '862022709072',
    projectId: 'flash-chat-3c761',
    storageBucket: 'flash-chat-3c761.firebasestorage.app',
    iosBundleId: 'com.example.flashChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwRmnsOJV3KyQO5nWCQ5EqFIeVMn-vgYU',
    appId: '1:862022709072:ios:7ea3359c926209294d0655',
    messagingSenderId: '862022709072',
    projectId: 'flash-chat-3c761',
    storageBucket: 'flash-chat-3c761.firebasestorage.app',
    iosBundleId: 'com.example.flashChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApcEFQaqbyjI47R0RjVQ8aBb6JnmqN0fE',
    appId: '1:862022709072:web:d28c32407322e53f4d0655',
    messagingSenderId: '862022709072',
    projectId: 'flash-chat-3c761',
    authDomain: 'flash-chat-3c761.firebaseapp.com',
    storageBucket: 'flash-chat-3c761.firebasestorage.app',
    measurementId: 'G-MZQ9RBSY8J',
  );

}